CMPUT301F24rabbit/carrot

- code/.gitignore
- code/app/build.gradle.kts
- code/app/src/main/AndroidManifest.xml
- code/app/src/main/java/com/example/goldencarrot/MainActivity.java
- code/app/src/main/java/com/example/goldencarrot/authentication/AccountService.java
- code/app/src/main/java/com/example/goldencarrot/authentication/AccountServiceImpl.java
- code/app/src/main/java/com/example/goldencarrot/data/db/UserRepository.java
- code/app/src/main/java/com/example/goldencarrot/data/model/user/User.java
- code/app/src/main/java/com/example/goldencarrot/data/model/user/UserImpl.java
- code/app/src/main/java/com/example/goldencarrot/data/model/user/UserUtils.java
- code/app/src/main/java/com/example/goldencarrot/views/SelectUserTypeActivity.java
- code/app/src/main/java/com/example/goldencarrot/views/SignUpActivity.java
- code/app/src/main/res/layout/activity_auth_sign_up.xml
- code/app/src/main/res/layout/activity_auth_sign_up_select_user_type.xml
- code/app/src/main/res/layout/activity_main.xml
- code/app/src/main/res/values/strings.xml
- code/build.gradle.kts
Implemented User Authentication
Connected to FireStore and Auth
**TODO:** 
Validate input data for user creation
Take user to welcome Page
Implement sign in/sign out
> Implemented User Authentication

- code/app/build.gradle.kts
- code/app/src/main/java/com/example/goldencarrot/MainActivity.java
- code/app/src/main/java/com/example/goldencarrot/views/AdminHomeActivity.java
- code/app/src/main/res/layout/activity_admin_home.xml
- code/app/src/test/java/com/example/goldencarrot/UserTest.java
made changes to gradle for junit 5 usage, created unit tests for getters of user class, created admin home view, made changes to main activity so that it retrieves the data of the currently logged in user, have not tested yet
> unit tests, admin home view

- code/app/build.gradle.kts
- code/app/src/main/java/com/example/goldencarrot/MainActivity.java
- code/app/src/main/java/com/example/goldencarrot/data/model/user/UserImpl.java
- code/app/src/main/java/com/example/goldencarrot/views/AdminHomeActivity.java
- code/app/src/main/res/layout/activity_admin_home.xml
- code/app/src/test/java/com/example/goldencarrot/UserTest.java
created unit tests for user which tests its getters, and if exception is thrown for invalid user type. created an admin home layout and admin home activity class.
> User unit tests, admin home view

- code/app/src/main/java/com/example/goldencarrot/views/EntrantHomeView.java
- code/app/src/main/java/com/example/goldencarrot/views/OrganizerHomeVIew.java
- code/app/src/main/res/layout/activity_admin_home.xml
- code/app/src/main/res/layout/activity_auth_sign_up.xml
- code/app/src/main/res/layout/activity_auth_sign_up_select_user_type.xml
- code/app/src/main/res/layout/activity_main.xml
- code/app/src/main/res/layout/entrant_home_view.xml
- code/app/src/main/res/layout/organizer_home_view.xml
Hi team,
I created the classes for Entrant and Organizer Homeviews as well as their XML files.
I did some work on the XML files visually, and also worked visually on the long in screens.
Tomorrow morning I plan on adding some functionality to some of the buttons I added.
> Entrant/Organizer Homepages + Log In Aesthetics

- code/app/src/main/res/layout/activity_admin_home.xml
> [BUG-FIX] fixed merge bug

- code/app/src/main/AndroidManifest.xml
- code/app/src/main/java/com/example/goldencarrot/MainActivity.java
- code/app/src/main/java/com/example/goldencarrot/data/db/UserRepository.java
- code/app/src/main/java/com/example/goldencarrot/views/AdminHomeActivity.java
- code/app/src/main/java/com/example/goldencarrot/views/OrganizerHomeVIew.java
- code/app/src/main/java/com/example/goldencarrot/views/OrganizerHomeView.java
- code/app/src/main/res/layout/organizer_home_view.xml
TODO do the same for Participant and Admin Users
> added Organizer home view log in on device feature

- code/app/src/main/AndroidManifest.xml
- code/app/src/main/java/com/example/goldencarrot/views/AdminHomeActivity.java
- code/app/src/main/java/com/example/goldencarrot/views/BrowseEventsActivity.java
- code/app/src/main/java/com/example/goldencarrot/views/EntrantHomeView.java
- code/app/src/main/java/com/example/goldencarrot/views/WaitlistActivity.java
- code/app/src/main/res/layout/activity_browse_events.xml
- code/app/src/main/res/layout/entrant_home_view.xml
- code/app/src/main/res/layout/entrant_waitlist.xml
- code/app/src/main/res/layout/entrant_waitlist_item.xml
these are US 1.02.01 and 3.04.01
> Updated for entrant leaving waitlist and admin browse events

- code/app/src/main/java/com/example/goldencarrot/views/EntrantHomeView.java
- code/app/src/main/res/layout/entrant_home_view.xml
> Please work

- code/app/src/main/java/com/example/goldencarrot/controller/EventController.java
- code/app/src/main/java/com/example/goldencarrot/data/db/UserRepository.java
- code/app/src/main/java/com/example/goldencarrot/data/db/WaitListDb.java
- code/app/src/main/java/com/example/goldencarrot/data/db/WaitListRepository.java
- code/app/src/main/java/com/example/goldencarrot/data/model/event/Event.java
- code/app/src/main/java/com/example/goldencarrot/data/model/event/EventConfigurator.java
- code/app/src/main/java/com/example/goldencarrot/data/model/waitlist/WaitListConfigurator.java
- code/app/src/main/java/com/example/goldencarrot/views/AdminAllUsersView.java
- code/build.gradle.kts
Added Event Controller method that should be used to update the Event Model
> Added Event location, date, and EventController.java

- code/app/src/androidTest/java/com/example/goldencarrot/EntrantHomeViewTest.java
- code/app/src/main/java/com/example/goldencarrot/views/EntrantHomeView.java
Pretty much done aside from some visuals and the tests.
> EntrantHomeView navagatiability 

- code/app/src/test/java/com/example/goldencarrot/UserTest.java
[BUG-FIX] we don't need to test firebase behavior (double checked this with a TA)
Although testing firebase updates, this would add complexity that will not be considered by our TAs when marking our project.
> [BUG-FIX] we don't need to test firebase behavior

- code/app/src/main/java/com/example/goldencarrot/data/db/UserRepository.java
- code/app/src/main/java/com/example/goldencarrot/data/model/user/User.java
- code/app/src/main/java/com/example/goldencarrot/data/model/user/UserImpl.java
- code/app/src/main/java/com/example/goldencarrot/views/AdminAllProfilesView.java
- code/app/src/main/java/com/example/goldencarrot/views/AdminProfileView.java
- code/app/src/main/java/com/example/goldencarrot/views/EntrantEditUserDetailsView.java
- code/app/src/main/java/com/example/goldencarrot/views/EntrantHomeView.java
- code/app/src/main/java/com/example/goldencarrot/views/OrganizerHomeView.java
- code/app/src/main/java/com/example/goldencarrot/views/SignUpActivity.java
- code/app/src/main/res/layout/entrant_edit_user_details.xml
- Users profile information is now displayed when they go to edit their profile
-  entrant should have only their waitlisted events show up
- started notification implementation with userand bool status
- made some cute toggles in the profile.
> Fixed edit profile and started implementing notifications

- code/app/src/main/java/com/example/goldencarrot/views/WaitlistActivity.java
> We shouldn't be deleting anymore when leaving waitlist

- code/app/src/main/java/com/example/goldencarrot/controller/NotificationController.java
- code/app/src/main/java/com/example/goldencarrot/data/db/NotificationRepository.java
- code/app/src/main/java/com/example/goldencarrot/data/model/notification/Notification.java
- code/app/src/main/java/com/example/goldencarrot/data/model/notification/NotificationAdapter.java
- code/app/src/main/java/com/example/goldencarrot/data/model/notification/NotificationUtils.java
- code/app/src/main/java/com/example/goldencarrot/views/EntrantEditUserDetailsView.java
- code/app/src/main/java/com/example/goldencarrot/views/EntrantNotificationsActivity.java
- code/app/src/main/res/layout/entrant_edit_user_details.xml
- code/app/src/main/res/layout/entrant_notifications_view.xml
- code/app/src/main/res/layout/notification_list.xml
this methods can be used to create consistent chosen and non chosen notifications in firebase
> added chosen and not chosen notification controller

- code/app/src/main/java/com/example/goldencarrot/data/db/EventRepository.java
- code/app/src/main/java/com/example/goldencarrot/data/model/event/Event.java
- code/app/src/main/java/com/example/goldencarrot/data/model/event/EventConfigurator.java
- code/app/src/main/java/com/example/goldencarrot/views/OrganizerCreateEvent.java
- code/app/src/main/res/layout/organizer_create_event.xml
Todo:
testing + alarming user when geolocation enabled
> [IMPROVEMENT] - added geolocation field for event creation

- code/app/src/main/java/com/example/goldencarrot/data/db/EventRepository.java
- code/app/src/main/java/com/example/goldencarrot/views/EntrantEventDetailsActivity.java
> [IMPROVEMENT] - added warning when geolocation enabled for events

- code/app/src/main/java/com/example/goldencarrot/data/db/UserRepository.java
- code/app/src/main/java/com/example/goldencarrot/views/EntrantEditUserDetailsView.java
Updated the switch in edit user details + updated the updateUserMethod to account for these boolean variables in firebase
> [IMPROVEMENT] - added update admin notif and organizer notif

- code/app/src/main/java/com/example/goldencarrot/views/EntrantHomeView.java
> [BUG-FIX] added deleted functionality

- code/app/src/main/java/com/example/goldencarrot/views/EntrantNotificationsActivity.java
user can cancel the joining the event and the status changes to cancelled in the waitlist
> [BUG-FIX] added cancel functionality for entrants

- code/app/src/main/java/com/example/goldencarrot/data/db/EventRepository.java
- code/app/src/main/java/com/example/goldencarrot/views/OrganizerCreateEvent.java
small bug fix
please merge this first
> [BUG-FIX] - fixed create waitlist with no event id.

- code/app/src/androidTest/java/com/example/goldencarrot/OrganizerNotificationTest.java
- code/app/src/androidTest/java/com/example/goldencarrot/OrganizerWaitlistTest.java
- code/app/src/main/java/com/example/goldencarrot/controller/WaitListController.java
- code/app/src/main/java/com/example/goldencarrot/data/model/user/UserUtils.java
- code/app/src/main/java/com/example/goldencarrot/views/EntrantNotificationsActivity.java
- code/app/src/main/java/com/example/goldencarrot/views/OrganizerEventDetailsActivity.java
- code/app/src/main/java/com/example/goldencarrot/views/OrganizerWaitlistView.java
- code/app/src/main/res/layout/activity_waitlisted_users_list.xml
- code/app/src/main/res/layout/popup_event_lists.xml
Organizer can cancel users that did not sign up on time
> [IMPROVEMENT] - organizer can cancel entrants that did not signup

- code/app/src/main/java/com/example/goldencarrot/data/db/WaitListDb.java
- code/app/src/main/java/com/example/goldencarrot/data/db/WaitListRepository.java
- code/app/src/main/java/com/example/goldencarrot/views/EntrantNotificationsActivity.java
Testing:
- Tested the behavior in Firebase
- No need to add more UI tests or Unit tests as they are already implemented for this activity, classes
> [IMPROVEMENT] - when user declines inv it draws replacement

- code/gradle/libs.versions.toml
> [BUG-FIX] - fixed main by changing the agp to 8.6.1 from 8.7.1

- code/app/src/androidTest/java/com/example/goldencarrot/EntrantNotificationsActivityTest.java
- code/app/src/main/AndroidManifest.xml
- code/app/src/main/java/com/example/goldencarrot/data/model/user/FacilityUserImpl.java
- code/app/src/main/res/drawable/poster_error.xml
- code/app/src/main/res/drawable/poster_placeholder.xml
android manifest was wrong and so was facilityuserimpl, its working now
> fixed main 

- code/app/src/androidTest/java/com/example/goldencarrot/EntrantEventDetailsActivityTest.java
- code/app/src/androidTest/java/com/example/goldencarrot/TestDataHelper.java
fixed a few tests that relied on hardcoded data
> [IMPROVEMENT] - fixed EntrantEventDetailsActivity.java tests

- code/app/src/main/java/com/example/goldencarrot/views/EntrantEditUserDetailsView.java
- code/app/src/main/java/com/example/goldencarrot/views/EntrantHomeView.java
- code/app/src/main/java/com/example/goldencarrot/views/SignUpActivity.java
I just re-added everything, so hopefully this works if you test it out?
> Try this Diego!

- code/app/src/main/java/com/example/goldencarrot/views/SignUpActivity.java
I hope this works for fixing the authentication in SignUpActivity.java
> User auth for firebase

- code/app/src/main/java/com/example/goldencarrot/data/db/UserRepository.java
- code/app/src/main/java/com/example/goldencarrot/views/SignUpActivity.java
* User auth for firebase
* adminNotification changed, now null should not display
---------
> Fixedauth (#180)

- code/app/src/main/java/com/example/goldencarrot/views/SignUpActivity.java
> [BUG-FIX] reverted change on SignUpActivity.java

- code/app/src/main/java/com/example/goldencarrot/views/EntrantEditUserDetailsView.java
Users no longer have to fear deterministically generated profile pictures when uploading a photo.
- Uploaded photos won't get overwritten
- Tell me why it isn't easy to compare paths from firebase storage???? Shouldn't that be a built in thing????????????
> US 01.03.03 and 01.03.02 Fix

- code/app/build.gradle.kts
- code/app/src/androidTest/java/com/example/goldencarrot/OrganizerEventTest.java
- code/app/src/androidTest/java/com/example/goldencarrot/TestDataHelper.java
- code/app/src/main/AndroidManifest.xml
- code/app/src/main/java/com/example/goldencarrot/controller/EventController.java
- code/app/src/main/java/com/example/goldencarrot/data/db/EventRepository.java
- code/app/src/main/java/com/example/goldencarrot/data/model/event/Event.java
- code/app/src/main/java/com/example/goldencarrot/data/model/event/EventArrayAdapter.java
- code/app/src/main/java/com/example/goldencarrot/data/model/event/EventConfigurator.java
- code/app/src/main/java/com/example/goldencarrot/data/model/event/EventRecyclerArrayAdapter.java
- code/app/src/main/java/com/example/goldencarrot/views/EntrantEventDetailsActivity.java
- code/app/src/main/java/com/example/goldencarrot/views/EntrantHomeView.java
- code/app/src/main/java/com/example/goldencarrot/views/EventDetailsAdminActivity.java
- code/app/src/main/java/com/example/goldencarrot/views/FacilityProfileActivity.java
- code/app/src/main/java/com/example/goldencarrot/views/OrganizerCreateEvent.java
- code/app/src/main/java/com/example/goldencarrot/views/OrganizerEventDetailsActivity.java
- code/app/src/main/java/com/example/goldencarrot/views/OrganizerHomeView.java
- code/app/src/main/res/layout/activity_browse_events.xml
- code/app/src/main/res/layout/activity_event_details.xml
- code/app/src/main/res/layout/activity_facility_profile.xml
- code/app/src/main/res/layout/entrant_event_details_view.xml
- code/app/src/main/res/layout/entrant_home_view.xml
- code/app/src/main/res/layout/event_list_item.xml
- code/app/src/main/res/layout/organizer_create_event.xml
- code/app/src/main/res/values/refs.xml
Reverts CMPUT301F24rabbit/carrot#187
> Revert "Poster Functionality "

- code/app/src/main/java/com/example/goldencarrot/data/db/EventRepository.java
- code/app/src/main/java/com/example/goldencarrot/views/OrganizerCreateEvent.java
fixed waitlist being always zero and made the poster optional
> [IMPROVEMENT] - fixing Ui tests

- code/app/src/androidTest/java/com/example/goldencarrot/OrganizerEventTest.java
- code/app/src/main/java/com/example/goldencarrot/data/db/EventRepository.java
fixed create event UI tests,
test now deletes creates the event and deletes it
> Fixed create event UI tests

- code/app/src/androidTest/java/com/example/goldencarrot/OrganizerNotificationTest.java
Now properly deletes test event after each test passes
> [IMPROVEMENT] OrganizerEventNotifications Clean Up events fix

- code/app/src/main/java/com/example/goldencarrot/data/model/event/EventArrayAdapter.java
- code/app/src/main/java/com/example/goldencarrot/views/EntrantHomeView.java
- code/app/src/main/java/com/example/goldencarrot/views/OrganizerEventDetailsActivity.java
Information and posters are loading for the preview of waitlisted events on EntrantHomeView
> Entrant should now see preview of their waitlisted events

- code/app/src/androidTest/java/com/example/goldencarrot/EntrantEventDetailsActivityTest.java
- code/app/src/androidTest/java/com/example/goldencarrot/SignUpActivityUITest.java
- code/app/src/androidTest/java/com/example/goldencarrot/TestDataHelper.java
- code/app/src/main/java/com/example/goldencarrot/views/EntrantEventDetailsActivity.java
> [IMPROVEMENT] - fixed Ui tests

- code/app/src/androidTest/java/com/example/goldencarrot/SignUpActivityUITest.java
> [IMPROVEMENT] - fixed SignUpActivity UI tests

- code/app/src/androidTest/java/com/example/goldencarrot/OrganizerGenerateQrCodeTest.java
- code/app/src/main/java/com/example/goldencarrot/views/OrganizerCreateEvent.java
+ fixed some other UI tests related to create event
> [IMPROVEMENT] - added OrganizerGenerateQrCodeTest.java

- code/app/src/main/java/com/example/goldencarrot/views/AdminAllProfilesView.java
- code/app/src/main/java/com/example/goldencarrot/views/AdminHomeActivity.java
- code/app/src/main/res/layout/activity_admin_all_users.xml
- code/app/src/main/res/layout/activity_admin_home.xml
Added the background changes to admin files
> Admin page background changes

- code/app/src/main/java/com/example/goldencarrot/views/EntrantHomeView.java
Now when an Entrant is accepted or chosen, that event will appear in the upcoming events list
> [IMPROVEMEWNT] Upcoming events now displayed

- code/app/src/main/java/com/example/goldencarrot/views/EntrantEditUserDetailsView.java
- code/app/src/main/java/com/example/goldencarrot/views/EntrantEventDetailsActivity.java
- code/app/src/main/java/com/example/goldencarrot/views/EntrantHomeView.java
Made some more javadoc comments
> Comments for Entrants

- code/app/src/main/java/com/example/goldencarrot/controller/CircleTransform.java
- code/app/src/main/java/com/example/goldencarrot/views/EntrantEditUserDetailsView.java
- code/app/src/main/java/com/example/goldencarrot/views/EntrantEventDetailsActivity.java
- code/app/src/main/java/com/example/goldencarrot/views/EntrantHomeView.java
- code/app/src/main/res/layout/entrant_edit_user_details.xml
Christmas came early my dudes.
> DON"T BE A SQUARE

- code/app/src/main/res/layout/activity_auth_sign_up.xml
> fixed signup view
